language: node_js
sudo: false
node_js: 8
services:
- docker
git:
  depth: 5
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- npm install -g yarn@v0.22.0
install:
- yarn install --ignore-optional
script:
- yarn run build
deploy:
  on:
    tags: true
  provider: npm
  email: sesispla@outlook.com
  api_key:
    secure: lCBcQo4x0U3WoKq4M/WIbZMiZh9b7i6w+8wY3laE9cACsDrD1HZMRRXbTuGPvVL7pcyedkT0/mGUrzFeqdfblyPoqfx60WvrN7Aq35vrgehy2uMyYw0MNsy99EYDn5bMjepL0Jbm4DxdyNn1Kbas+tNyPhIBWZ1IZDAsqJFJY2rF4E9AsB3xwU3D28KLAiwWyYNaNYRHK98DKzuoAujl4QDfbpJI599cs2w6g4Ir1DtvxE7FfI1bDwF2IIwzqXVc5HK7Fos7pKB+bTD3PC9+xVvYyTBa6NDlu06T61b56m8zO5TSBu5TD9IDm0ugwKuZx+2GGNsIvsDCCAG+VUTt4AxQXCT0J4VY1aryn/QjKNKQ3PnZc8OTVEfzrj+4K/sJEz+7OAc+SQmzVXiSKzhKyOkpNN/cbOJbP+sQ+3B/IagDuDyCgpnIYbDcjEkD7G1jfw6Kz7J/xEO/rB1M6lC4zqxgre85ooJeetdEVVL4HBobaqTgdhPA2++Al5mI+qDF/RHzaNJGb97D2+GijyaFddlGNEnFMT/fA0TU3ogVMg4RBQH2Hmxa/DGie+hPO6g5bj2a+p1C8UFKvdWFv5NXrsNC/ej/2cnXssdKuCPl52XKd8i9333w424ZgGVXEyfjEMkH1k+e/t61Okj1H90iAl0CNUtmaBA7HQiq+xPei1w=
